<?php
	include_once('ressources/class.templates.inc');
	include_once('ressources/class.ldap.inc');
	include_once('ressources/class.users.menus.inc');
	include_once('ressources/class.mail.inc');



	$page=CurrentPageName();
	$tpl=new templates();
	
	$users=new usersMenus();
	if(!$users->AsPostfixAdministrator){
		$error=$tpl->_ENGINE_parse_body("{ERROR_NO_PRIVS}");
		echo "alert('$error')";
		die();
	}
	
	if(isset($_GET["popup"])){popup();exit;}
	if(isset($_GET["TEST_MAIL_SUBJECT"])){sendmail_tests();exit;}
js();


function js(){
	
	$tpl=new templates();
	$page=CurrentPageName();
	$title=$tpl->_ENGINE_parse_body('{send_a_test_mail}');
	$rcpt=$_GET["rcpt"];
	$html="
	function send_a_test_mail_load(){
			RTMMail(450,'$page?popup=yes&rcpt=$rcpt','$title');
		}
		
		var x_send_a_test_mail_start= function (obj) {
			var tempvalue=obj.responseText;
			document.getElementById('testmaildiv').innerHTML=tempvalue;
		}		
		
		
	function send_a_test_mail_start(){
		var XHR = new XHRConnection();
		XHR.appendData('TEST_MAIL_SUBJECT',document.getElementById('TEST_MAIL_SUBJECT').value);
		XHR.appendData('TEST_MAIL_FROM',document.getElementById('TEST_MAIL_FROM').value);
		XHR.appendData('rcpt','$rcpt');
		document.getElementById('testmaildiv').innerHTML='<center><img src=\"img/wait_verybig.gif\"></center>';
		XHR.sendAndLoad('$page', 'GET',x_send_a_test_mail_start);
	}
	
	function send_a_test_mail_Enter(e){
		if(checkEnter(e)){send_a_test_mail_start();return;}
	}
	
	send_a_test_mail_load()";
	
	echo $html;
	
	
}


function sendmail_tests(){
	$tpl=new templates();
	$TEST_MAIL_SUBJECT=$_GET["TEST_MAIL_SUBJECT"];
	$TEST_MAIL_FROM=$_GET["TEST_MAIL_FROM"];
	$rcpt=$_GET["rcpt"];
	$users=new usersMenus();

	
	setcookie('TEST_MAIL_SUBJECT', $TEST_MAIL_SUBJECT, (time() + 3600));
	setcookie('TEST_MAIL_FROM', $TEST_MAIL_FROM, (time() + 3600));
	$mail=new simplemail();
	
	$mail->addrecipient($rcpt);
	$mail->addreturnpath($TEST_MAIL_FROM);
	$mail->addfrom($TEST_MAIL_FROM);
	$mail->subject=$TEST_MAIL_SUBJECT;
	$mail->set_mode="socket";
	
	$mail->html="
	<html>
	<head>$TEST_MAIL_SUBJECT</head>
	<body style='padding:20px;margin:30px'>
	<center>
	<div style='border:5px solid #005447;padding:10px;margin:5px;width:450px;text-align:left'>
	<H1 style='font-family:arial;font-size:18px;color:#005447'>$TEST_MAIL_SUBJECT</H1>
	<p style='font-family:arial;font-size:13px'>This is a test mail generated by artica <b>$users->ARTICA_VERSION</b><br>
	it was sended to be sure that the routing mail is available.<br>
	<br>
	You don't need to store this mail on your Mailbox.<br>
	</p>
	<p style='font-family:arial;font-size:13px'>Please delete it</p>
	<hr>
	<p style='font-family:arial;font-size:13px;text-align:right'>The mail server administrator.</p>
	</div>
	</center>
	</body>
	</html>";
	
	if($mail->sendmail()){echo $tpl->_ENGINE_parse_body("<H2>{success}</H2>");return;}
	echo "<div style='color:red'>". nl2br($mail->error_log)."</div>";
	
}

function popup(){
	$rcpt=$_GET["rcpt"];
	if($_COOKIE["TEST_MAIL_SUBJECT"]==null){$_COOKIE["TEST_MAIL_SUBJECT"]="This is a test mail...";}
	$html="
	<H2>$rcpt</h2>
	<p style='font-size:14px'>{send_a_test_mail_text}</p>
	<table style='width:100%'>
		<tr>
			<td valign='top' class=legend>{from}:</td>
			<td>". Field_text("TEST_MAIL_FROM",$_COOKIE["TEST_MAIL_FROM"],"font-size:15px;padding:3px",
			null,null,null,false,"send_a_test_mail_Enter(event)")."</td>
		</tr>
		<tr>
			<td valign='top' class=legend>{subject}:</td>
			<td>". Field_text("TEST_MAIL_SUBJECT",$_COOKIE["TEST_MAIL_SUBJECT"],"font-size:15px;padding:3px",
			null,null,null,false,"send_a_test_mail_Enter(event)")."</td>
		</tr>
	<tr>
		<td colspan=2 align='right'>
			<hr>
			". button("{send}","send_a_test_mail_start()")."</td>
	</tr>		
	</table>
	<div id='testmaildiv' style='height:150px;overflow:auto'></div>
	
	
	";
	
	$tpl=new templates();
	echo $tpl->_ENGINE_parse_body($html);
	
	
}

?>